FROM node:20-alpine
RUN apk add --no-cache openssl openssl-dev
WORKDIR /app
COPY package*.json ./
COPY node_modules ./node_modules
COPY . .
EXPOSE 4000
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/app.ts"]
